name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        run: |
          echo "Generating snake animation..."
          # your script here

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "stimpy3"
          author_email: "chimpbowl502@gmail.com"
          message: "Generate Snake"
          add: "."
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
